version: '3'

services:
  ssh-tg-bot:
    container_name: ssh-bot
    build: .
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - AUTHORIZED_USER=${AUTHORIZED_USER}
      - SERVER_IP=${SERVER_IP}
      - SSH_USERNAME=${SSH_USERNAME:-root}
      - SSH_PASSWORD=${SSH_PASSWORD}
    # Удаляем монтирование SSH ключей, так как они не используются 